server:
  port: 80
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://tmlh.xyz:3306/tmlh-forum?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: tx
    password: tx666

#去除thymeleaf标签验证
  thymeleaf:
    cache: false
  session:
    store-type: none


#security.basic.enabled = false

#登陆页面
tmlh:
  security:
    browser:
      login-page: /admin/login
      sign-up-url: /sign-Up
#图片验证码
    code:
      image:
        width: 146
        height: 33
#社交
    social:
      qq:
        app-id: 101559281
        app-secret: c8b086c46dae6ba951e07bcf00d7a662
        provider-id: qq
