spring:
  profiles:
    active:
    - dev
    
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.207.5.177:3306/tmlh-forum?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
    username: tx
    password: tx666
    druid:
      connection-init-sqls: set names utf8mb4;
        