server:
  port: 80
  
spring:
#去除thymeleaf标签验证
  thymeleaf:
    content-type: text/html  

  session:
    store-type: none


#security.basic.enabled = false

#登陆页面
tmlh:
  security:
    browser:
      login-page: /admin/login
      sign-up-url: /sign-Up
#图片验证码
    code:
      image:
        width: 146
        height: 33
#社交
    social:
      qq:
#        app-id: 101559281
#        app-secret: c8b086c46dae6ba951e07bcf00d7a662
        app-id: 101564529
        app-secret: 79c879ffc9e01c19a63b674bc9eb91b9

        provider-id: qq

        
mybatis-plus:
    typeEnumsPackage: xyz.tmlh.core.enums  
    mapper-locations: classpath:mapper/*.xml  
    global-config:
      banner: false
        