server:
  port: 80
  
spring:
  session:
    store-type: none
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/tmlh-forum?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
    username: root
    password: 
    druid:
      connection-init-sqls: set names utf8mb4;
  freemarker:
    settings:
      classic_compatible: true        
        

#security.basic.enabled = false

#登陆页面
tmlh:
  security:
    browser:
      login-page: /login
      sign-up-url: /signup
#图片验证码
    code:
      image:
        width: 146
        height: 33
#社交
    social:
      qq:
        app-id: 101559281
        app-secret: c8b086c46dae6ba951e07bcf00d7a662
#        app-id: 101564529
#        app-secret: 79c879ffc9e01c19a63b674bc9eb91b9
      github:
        app-id: 6161f2cee4ad8fe7e89a
        app-secret: bdef1d6d79a74a555f878c128cfc1eb6cb8482dc
      gitee:
        app-id: d32257f38f59d5ee03c6955237950bd04a2c84d56a1fb121a8898b52df4669d0
        app-secret: 508ae3161a143c74618e55dcca724ecb6d0d5cba5c34e4a3ee9f3c612d36827a        

        
mybatis-plus:
    typeEnumsPackage: xyz.tmlh.core.enums  
    mapper-locations: classpath:mapper/*.xml  
    global-config:
      banner: false
        